### ISSUE TITLE
Authelia & Invalid value for name

### ISSUE THREAD

**Issue by shrunbr** [leg100/otf#768]
Hi there, I am opening this issue more for a documentation purpose. It can be closed immediately, I just hope this will help someone else in the future...it took me about a day and a half to figure this out. This worked just fine in previous versions of OTF and Authelia but with the latest versions I found this fix is required. 

**Stack:**
- OTF 0.3.19+
- Authelia 4.39.1+

**Symptoms:** After successful authentication with Authelia, you hit the callback OTF URL and then get the error: `invalid value for name: username must be non-empty `.

**Resolution:** 
1. Create an OTF claim policy under oidc
```
identity_providers:
  oidc:
    claims_policies:
      otf_claims:
        id_token: ['email', 'name', 'preferred_username']
        access_token: []
        id_token_audience_mode: specification
        custom_claims:
          email:
            attribute: email
          name:
            attribute: display_name
          preferred_username:
            attribute: username
```

2. Attach the claim policy to the OTF client
```
  clients:
      - client_id: 'kAleEGx...koa6RUOm6'
        client_name: 'OTF'
        client_secret: '$pbkdf2-sha512$310000....paSc0ZUEw'
        public: false
        authorization_policy: 'one_factor'
        require_pkce: false
        redirect_uris:
          - 'https://otf.mydomain.com/oauth/Authelia/callback'
        scopes:
          - 'openid'
          - 'profile'
          - 'email'
        claims_policy: otf_claims
        userinfo_signed_response_alg: 'none'
        token_endpoint_auth_method: 'client_secret_basic'
```

3. Restart Authelia

After applying the claim policy you should be able to successfully authenticate to OTF. This same fix could also be applied to Cloudflare Zero Trust if you're having an issue there as well.
